# Use Gradle to build the services
FROM gradle:8.8-jdk17 as build

WORKDIR /app

# Copy the Gradle configuration files
COPY ./spring/test-services/order/build.gradle.kts ./spring/test-services/settings.gradle.kts ./

# Download dependencies (this layer will be cached unless build.gradle.kts changes)
RUN gradle dependencies --no-daemon

# Copy the source code
COPY ./spring/test-services/order/src ./src

# Build the application
RUN gradle build --no-daemon --build-cache


# Use a smaller base image for runtime
FROM openjdk:21-jdk-slim

WORKDIR /app

# Copy the built JARs for both services
COPY --from=build /app/build/libs/*.jar /app/order.jar

# Expose the ports
EXPOSE 6443

# Start both services
CMD ["java", "-jar", "/app/order.jar"]
