# File: docker-compose.yml
version: '3.8'

services:
  nginx1:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8081:443"
    environment:
      - VAULT_ADDR=https://vault:8200
      - VAULT_CACERT=/etc/ssl/certs/vault-ca.crt
      - ROLE_ID=<ROLE_ID_1>
      - SECRET_ID=<SECRET_ID_1>
      - COMMON_NAME=nginx1.example.com
    volumes:
      - ./nginx-config/nginx1.conf:/etc/nginx/nginx.conf:ro
      - ./vault-config/vault.crt:/etc/ssl/certs/vault-ca.crt:ro
    networks:
      - mtls-network

  nginx2:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8082:443"
    environment:
      - VAULT_ADDR=https://vault:8200
      - VAULT_CACERT=/etc/ssl/certs/vault-ca.crt
      - ROLE_ID=<ROLE_ID_2>
      - SECRET_ID=<SECRET_ID_2>
      - COMMON_NAME=nginx2.example.com
    volumes:
      - ./nginx-config/nginx2.conf:/etc/nginx/nginx.conf:ro
      - ./vault-config/vault.crt:/etc/ssl/certs/vault-ca.crt:ro
    networks:
      - mtls-network

  nginx3:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8083:443"
    environment:
      - VAULT_ADDR=https://vault:8200
      - VAULT_CACERT=/etc/ssl/certs/vault-ca.crt
      - ROLE_ID=<ROLE_ID_3>
      - SECRET_ID=<SECRET_ID_3>
      - COMMON_NAME=nginx3.example.com
    volumes:
      - ./nginx-config/nginx3.conf:/etc/nginx/nginx.conf:ro
      - ./vault-config/vault.crt:/etc/ssl/certs/vault-ca.crt:ro
    networks:
      - mtls-network

  vault:
    build:
      context: .
      dockerfile: Dockerfile-vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - ./vault-config:/vault/config
      - ./vault-data:/vault/data
    command: server

networks:
  mtls-network:
    driver: bridge