# Use Gradle to build the services
FROM gradle:8.8-jdk17 as build

WORKDIR /app

# Copy and build the Order service
COPY ./spring/test-services/order/build.gradle.kts ./spring/test-services/settings.gradle.kts /app/order/
COPY ./spring/test-services/order/src /app/order/src
RUN cd order && gradle build --no-daemon


# Use a smaller base image for runtime
FROM openjdk:21-jdk-slim

WORKDIR /app

# Copy the built JARs for both services
COPY --from=build /app/order/build/libs/*.jar /app/order.jar

# Expose the ports
EXPOSE 8081

# Start both services
CMD ["sh", "-c", "java -jar /app/order.jar"]
