# File: docker-compose.yml
services:
  nginx1:
    build:
      context: .
      dockerfile: Dockerfile-nginx
      args:
        SERVER_NAME: nginx1
    ports:
      - "8081:8081"
    volumes:
      - ./nginx-logs/nginx1:/var/log/nginx
    networks:
      - mtls-network

  nginx2:
    build:
      context: .
      dockerfile: Dockerfile-nginx
      args:
        SERVER_NAME: nginx2
    ports:
      - "8082:8082"
    volumes:
      - ./nginx-logs/nginx2:/var/log/nginx
    networks:
      - mtls-network

  nginx3:
    build:
      context: .
      dockerfile: Dockerfile-nginx
      args:
        SERVER_NAME: nginx3
    ports:
      - "8083:8083"
    volumes:
      - ./nginx-logs/nginx3:/var/log/nginx
    networks:
      - mtls-network

  vault:
    build:
      context: .
      dockerfile: Dockerfile-vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - ./vault-config:/vault/config
      - ./vault-data:/vault/data
    command: server

networks:
  mtls-network:
    driver: bridge