spring:
  application:
    name: order
  ssl:
    bundle:
      jks:
        order:
          key:
            alias: order
          keystore:
            location: classpath:order.jks
            password: changeit
          truststore:
            location: classpath:client-truststore.jks
            password: changeit
  webflux:
    ssl:
      bundle: order
    webclient:
      ssl:
        hostname-verification: false

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
        ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/uptrace
    platform: postgres
    username: uptrace
    password: uptrace_password
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  
  tracing:
    sampling:
      probability: 1.0

  endpoint:
    health:
      show-details: always
    trace:
      show-details: always
      
  otlp:
    tracing:
      endpoint: "http://localhost:14318/v1/traces"
      compression: "none"
      timeout: 10s
      headers:
        uptrace-dsn: "http://new@0.0.0.0:14318?grpc=14317"

    metrics:
      export:
        url: "http://localhost:14318/v1/metrics"
        aggregationTemporality: "cumulative"
        headers:
          uptrace-dsn: "http://new@0.0.0.0:14318?grpc=14317"
          protocol: grpc
        step: 30s

logging:
  level:
    root: INFO
    org:
      springframework:
        security:
          web: DEBUG
    com:
      innowate:
        services:
          order: DEBUG
    io.micrometer: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} [${spring.application.name:},%X{traceId:-},%X{spanId:-}] [%t] %logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

server:
  port: 6443
  ssl:
    bundle: order
    client-auth: NEED

payment:
  service:
    url: https://payment:8443
