spring:
  application:
    name: order
  ssl:
    bundle:
      jks:
        order:
          key:
            alias: order
          keystore:
            location: classpath:order.jks
            password: changeit
          truststore:
            location: classpath:client-truststore.jks
            password: changeit
  webflux:
    ssl:
      bundle: order
    webclient:
      ssl:
        hostname-verification: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    trace:
      show-details: always

  otlp:
    metrics:
      export:
        url: "http://uptrace:14318/v1/metrics"
        aggregationTemporality: "cumulative"
        headers:
          uptrace-dsn: "http://spring-secret@uptrace:14318"
          protocol: grpc
        step: 30s

logging:
  config: classpath:logback-spring.xml
  # file:
  #   name: /spring/logs/application.log
  level:
    root: INFO
    org:
      springframework:
        security:
          web: DEBUG
    com:
      innowate:
        services:
          payment: DEBUG
    
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 6443
  ssl:
    bundle: order
    client-auth: NEED

payment:
  service:
    url: https://localhost:8443