spring:
  application:
    name: payment
  ssl:
    bundle:
      jks:
        payment: # Give your bundle a name
          key:
            alias: payment
          keystore:
            location: classpath:payment.jks
            password: changeit
          truststore:
            location: classpath:client-truststore.jks
            password: changeit
  webflux:
    ssl:
      bundle: payment
    webclient:
      ssl:
        hostname-verification: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    trace:
      show-details: always

  otlp:
    metrics:
      export:
        url: "http://uptrace:14318/v1/metrics"
        aggregationTemporality: "cumulative"
        headers:
          uptrace-dsn: "http://spring-secret@uptrace:14318"
          protocol: grpc
        step: 30s
  

server:
  port: 8443
  ssl:
    bundle: payment # Reference your SSL bundle here
    client-auth: NEED

order:
  service:
    url: https://localhost:6443

logging:
  level:
    root: INFO
    org:
      springframework:
        security:
          web: DEBUG
    com:
      innowate:
        services:
          payment: DEBUG
    
  config: classpath:logback-spring.xml

  # file:
  #   name: /spring/logs/application.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"