spring:
  application:
    name: payment
  ssl:
    bundle:
      jks:
        payment:
          key:
            alias: payment
          keystore:
            location: classpath:payment.jks
            password: changeit
          truststore:
            location: classpath:client-truststore.jks
            password: changeit

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
        ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/uptrace
    platform: postgres
    username: uptrace
    password: uptrace_password
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    enabled: true
    propagation:
      type: w3c
    baggage: 
      enabled: true
      correlation:
        enabled: true
    sampling:
      probability: 1.0

  endpoint:
    health:
      show-details: always

  otlp:
    tracing:
      endpoint: "http://localhost:14318/v1/traces"
      compression: "gzip"
      timeout: 10s
      headers:
        uptrace-dsn: "http://new@0.0.0.0:14318?grpc=14317"

    metrics:
      export:
        url: "http://localhost:14318/v1/metrics"
        aggregationTemporality: "cumulative"
        headers:
          uptrace-dsn: "http://new@0.0.0.0:14318?grpc=14317"
          protocol: grpc
        step: 30s

server:
  port: 8443
  ssl:
    bundle: payment
    client-auth: NEED

order:
  service:
    url: https://order:6443

logging:
  level:
    root: INFO
    org:
      springframework:
        security:
          web: DEBUG
    com:
      innowate:
        services:
          payment: DEBUG
    io.opentelemetry: DEBUG
    io.micrometer.tracing: DEBUG

  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false